---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Сайт должен иметь мобильную версию
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- Возможность регистрации пользователя
- Возможность авторизации пользователя
- Возможность указать контактные данные пользователя при оформлении заказа
- На странице корзины пользователь может указать количество единиц добавленного в корзину товара
- Сайт должен иметь возможность изменения валюты
