---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. 
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Возможность регистрации пользователя
  - Возможность авторизации пользователя
  - Возможность указать контактные данные пользователя при оформлении заказа (номер телефона, адрес, электронная почта)
  - Пользователь должен иметь возможность выбрать способ оплаты заказа
  - Пользователь должен иметь возможность выбрать способ доставки заказа
  - После оформления заказа пользователь должен получить письмо на электронную почту с информацией о своем заказе
  - На странице корзины пользователь может указать количество единиц добавленного в корзину товара
  - Сайт должен иметь возможность изменения валюты
  - На странице магазина должно быть указано количество страниц в каталоге
  - Фильтр по цене должен обрабатывать числа с дробной частью
  
